var tab_server = ["https://dub01.online.tableau.com/t/emeasalesdemo/views/FINANCE/Cockpit","https://dub01.online.tableau.com/t/emeasalesdemo/views/FINANCE/BalanceSheet","https://dub01.online.tableau.com/t/emeasalesdemo/views/FINANCE/Analysis-KPIPerformance",""];
  var tab_filter=[[],[],[],[]];
  var tab_web=[{"key":"1","val":"false"},{"key":"0","val":"true"},{"key":"2","val":"false"},{"key":"3","val":"false"}];
  var tab_ask=[{"key":"0","val":""},{"key":"3","val":""},{"key":"1","val":""},{"key":"2","val":""}];
  var tab_param=[["Current Year"],["Current Year"],["Current Year"],[]]; 
  var tab_text=[{"key":"Filter-text-Current Year","val":"Year"},{"key":"Viz-3-text","val":"Performance"},{"key":"Viz-2-text","val":"Balance"},{"key":"WebEdit-text","val":"Edition"},{"key":"User-text","val":"%20Paul%20Auditor"},{"key":"Download-Data-text","val":"Download"},{"key":"Action-text","val":"Search"},{"key":"Viz-1-text","val":"Cockpit"},{"key":"Viz-4-text","val":"Viz%204%20"},{"key":"Reset-Viz-text","val":"Reset"},{"key":"PrivacyPolicy-text","val":"Privacy%20Policy%20"},{"key":"Filter-text-DASH_SECURITY_PARAM","val":"DASH_SECURITY_PARAM"},{"key":"Terms-text","val":"Terms%20%26%20Conditions%20"},{"key":"AskData-text","val":"Ask%20data%20"}];
  var tab_img=[{"key":"img-logo","val":"https://logodix.com/logo/1666977.png"},{"key":"img-avatar","val":"https://d29fhpw069ctt2.cloudfront.net/icon/image/84587/preview.svg"}];
  var tab_action=[{"key":"2","val":"true"},{"key":"0","val":"true"},{"key":"1","val":"true"},{"key":"3","val":"false"}];
  var title_index="audit";